
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://abee369.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /itsabhinaya

# Google tracking id

google-tracking-id: "UA-99119647-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############
lang: "en"
author: "Abhinaya Konduru"
title: "Abhinaya"
description: "About Abhinaya Konduru. Opinions expressed are mine."
keywords: "it's abhinaya, itsabhinaya, its abhinaya, Abhinaya, abhi, abhinayakonduru, konduru, abhikonduru, abhi konduru, abhinaya konduru"
favicon: "/img/logo.ico"

################
# Header layout #
################

# black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/banner.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 200
lines: # You can add HTML Tags in the Text
  - text: The first draft of anything is shit.
  - text: Dream big and dare to fail.
  - text: If You’re Offered a Seat on a Rocket Ship, You Don’t Ask What Seat. You Just Get On.
me-img: "../img/abhinaya.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 20

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "itsabhinayaofficial@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Abhinaya Konduru is VC at M25 Group. She loves startups, data, and videos."
author_blurb_image: "/img/abhinaya.jpg"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/itsabhinaya"
  - title: "linkedin"
    url: "http://linkedin.com/in/itsabhinaya/"
  - title: "medium"
    url: "https://medium.com/@itsabhinaya"
  - title: "pencil"
    url: "https://200wordsaday.com/writers/itsabhinaya"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Thoughts: 'latest-post'
  # Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
